{{-- Printable document layout (A4). Use the browser's Print → "Save as PDF". --}}
@props(['title', 'subtitle' => null, 'orientation' => 'portrait'])

<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $title }} · EduVers</title>
    @fonts
    @vite(['resources/css/app.css'])
    <style>
        @page { size: A4 {{ $orientation === 'landscape' ? 'landscape' : 'portrait' }}; margin: 12mm; }
        @media print {
            .no-print { display: none !important; }
            html, body { background: #fff !important; }
            * { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            thead { display: table-header-group; }
            tr { break-inside: avoid; }
        }
    </style>
</head>
<body class="bg-ivory-200 font-sans text-ink-900 antialiased">
    {{-- Toolbar (hidden when printing) --}}
    <div class="no-print sticky top-0 z-10 border-b border-white/10 bg-ink-900 text-ivory">
        <div class="mx-auto flex max-w-5xl flex-wrap items-center justify-between gap-3 px-6 py-3">
            <p class="text-sm text-slate-300">Tip: choose <strong class="text-gold-300">Save as PDF</strong> in the print dialog to get a PDF.</p>
            <div class="flex items-center gap-2">
                {{ $actions ?? '' }}
                <button type="button" onclick="window.print()" class="btn-gold px-4 py-2 text-xs">
                    <x-icon name="printer" class="size-4" /> Print / Save as PDF
                </button>
                <button type="button" onclick="window.close()" class="rounded-lg px-3 py-2 text-xs text-slate-300 hover:text-white">Close</button>
            </div>
        </div>
    </div>

    <main @class([
        'mx-auto my-8 bg-white p-10 shadow-elevated print:m-0 print:max-w-none print:p-0 print:shadow-none',
        'max-w-[297mm]' => $orientation === 'landscape',
        'max-w-[210mm]' => $orientation !== 'landscape',
    ])>
        {{-- Letterhead --}}
        <header class="flex items-center gap-5 border-b-2 border-gold-500 pb-5">
            <x-logo class="size-16" />
            <div class="flex-1">
                <p class="font-serif text-xl font-semibold leading-tight">Movers Institute of Technology and Education</p>
                <p class="font-serif text-sm text-champagne-dark italic">Transform, Learn, Lead</p>
            </div>
            <div class="text-right text-xs text-slate-500">
                <p class="font-semibold uppercase tracking-luxe text-ink-800">EduVers LMS</p>
                <p>{{ now()->format('F j, Y g:i A') }}</p>
            </div>
        </header>

        <div class="mt-6 mb-6">
            <h1 class="font-serif text-2xl font-semibold">{{ $title }}</h1>
            @if ($subtitle)
                <p class="mt-1 text-sm text-slate-600">{{ $subtitle }}</p>
            @endif
        </div>

        {{ $slot }}

        <footer class="mt-10 flex items-end justify-between gap-6 border-t border-ivory-300 pt-4 text-xs text-slate-500">
            <p>Generated by {{ auth()->user()->name }} via EduVers · {{ now()->format('Y-m-d H:i') }}</p>
            <div class="w-56 text-center">
                <div class="border-b border-slate-400 pb-6"></div>
                <p class="mt-1">Signature over printed name</p>
            </div>
        </footer>
    </main>
</body>
</html>
